### PR TITLE
Support for aws session_token

### PR DESCRIPTION
**Pull request by trzeciak**
AWS offers a third component of aws-credentials: `access_key_id` + `secret_access_key` + **`session_token`**, see [LINK](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html) (and livekit/egress currently only supports two of them).

I've already asked the same question on livekit/slack [LINK](https://livekit-users.slack.com/archives/C01KVTJH6BX/p1717084987144909). I was directed to this place by cool people, for which I thank them.

PS: I tried passing the `session_token` via `metadata`, but it doesn't seem to work (mp4 file wasn't placed on S3), like:
```
            …
            "s3": {
                "access_key": "<access_key_id>",
                "secret": "<secret_access_key>",
                "metadata": {
                    "X-Amz-Security-Token": "<session_token>"
                },
                …
            }
            …
```
(the aws documentation does not confirm that this should work at all, links: [Working with object metadata - Amazon Simple Storage Service](https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html), [Using temporary credentials with AWS resources - AWS Identity and Access Management (](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html)[amazon.com](http://amazon.com/)[)](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html), [Signing and authenticating REST requests - Amazon Simple Storage Service](https://docs.aws.amazon.com/AmazonS3/latest/userguide/RESTAuthentication.html#UsingTemporarySecurityCredentials))

### CODE REVIEW

**Comment by trzeciak** [comment]
Did they fail the tests or do I need to do something extra?

**Comment by trzeciak** [comment]
Is there any way I can help with this (any tip?), or do I just have to patiently wait for someone from livekit (like you)?

**Comment by frostbyte73** [comment]
> Is there any way I can help with this (any tip?), or do I just have to patiently wait for someone from livekit (like you)?

I just merged https://github.com/livekit/protocol/pull/734 yesterday, can you update protocol and use `SessionToken` from the S3Upload in the request as well? I'll run the tests and merge after that

**Comment by trzeciak** [comment]
Okej 😅 (but today I tried 'golang getting started' first time 😄)
To be clear, I run these commands in the `egress` dir-repo:
```sh
❯ go mod download
❯ go get github.com/livekit/protocol@v1.17.1-0.20240612003900-1dd95af54240
go: downloading golang.org/x/mod v0.17.0
go: upgraded github.com/livekit/protocol v1.16.1-0.20240513145257-511f517b1abf => v1.17.1-0.20240612003900-1dd95af54240
go: upgraded github.com/livekit/psrpc v0.5.3-0.20240403150641-811331b106d9 => v0.5.3-0.20240526192918-fbdaf10e6aa5
```
This also updated the version of `livekit/psrpc` and added dependencies to `golang.org/x/mod`, see: [LINK](https://github.com/livekit/egress/pull/696/commits/e1f1d098866673d2e27dc7e72aa4d39090805aac).

BTW: My go version:
```sh
❯ go version
go version go1.22.4 darwin/arm64
```
PS: Hm.. maybe I should run this on Linux?

**Review by frostbyte73 — APPROVED** [review]

**Comment by trzeciak** [comment]
Hey, is there a known ETA release date for the next version of egress (and next deploy to livekit cloud/prod)?  
I'm asking in the context of session token support.

**Pull request merged**
