### PR TITLE
Support for Aliyun OSS as a storage backend

### PR DESCRIPTION
**Pull request by tomxiong**
This pull request depends on https://github.com/livekit/protocol/pull/234 .
@davidzhao , please help to review the two pull requests.

Thanks.

### CODE REVIEW

**Comment by tomxiong** [comment]
The related issue is: https://github.com/livekit/egress/issues/114

**Comment by frostbyte73** [comment]
hey @tomxiong, can you update protocol to 41f5b55c9507c061d4b3c45d80aefccf915ae388

**Comment by tomxiong** [comment]
@frostbyte73 ， Done. Please help to review.

**Review by frostbyte73 — CHANGES_REQUESTED** [review]
updateFileParams in params.go needs to be updated as well

**Comment by tomxiong** [comment]
@frostbyte73 , I update the params.go as you mentioned. Please help to review again.

**Comment by frostbyte73** [comment]
> @frostbyte73 , I update the params.go as you mentioned. Please help to review again.

it looks like the changes haven't been pushed yet

**Comment by tomxiong** [comment]
@frostbyte73 , sorry about that, I push code.

**Comment by tomxiong** [comment]
Done @frostbyte73

**Review by frostbyte73 — APPROVED** [review]

**Pull request merged**
